-- ==========================================
-- 01_schema.sql
-- VIEOS Supabase Database Schema
-- ==========================================

-- 1. Custom Types (Enums)
CREATE TYPE public.event_type AS ENUM ('special', 'regular');
CREATE TYPE public.cheki_type AS ENUM ('solo', 'group');
CREATE TYPE public.order_status AS ENUM ('pending', 'paid', 'verified', 'cancelled');

-- 2. Members Table
CREATE TABLE public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    role VARCHAR(100),
    fullname VARCHAR(255),
    birth_date VARCHAR(100),
    instagram VARCHAR(100),
    theme_color VARCHAR(20),
    image_url TEXT,
    symbol VARCHAR(10),
    vibe VARCHAR(255),
    catchphrase TEXT,
    jiko TEXT,
    highlight BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Events Table
CREATE TABLE public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type public.event_type NOT NULL,
    event_date VARCHAR(50), -- e.g., 'FEB 14' to match your constants
    event_time VARCHAR(50), -- e.g., '19:00 WIB'
    location VARCHAR(255),
    status VARCHAR(20) DEFAULT 'ongoing',
    po_deadline VARCHAR(50),
    theme VARCHAR(255),
    lineup JSONB DEFAULT '["GROUP"]'::jsonb,
    available_members JSONB DEFAULT '["GROUP"]'::jsonb,
    special_prices JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Discography (Albums/Singles)
CREATE TABLE public.discography (
    id VARCHAR(50) PRIMARY KEY, -- String ID like 'memoire', 'legacy'
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255),
    artist_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Songs
CREATE TABLE public.songs (
    id VARCHAR(50) PRIMARY KEY, -- e.g., '01'
    discography_id VARCHAR(50) REFERENCES public.discography(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255),
    duration VARCHAR(20),
    lyrics TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Orders Table (sesuai server/controllers/orderController.js — checkout & admin)
CREATE TABLE public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NOT NULL,
    event_id BIGINT REFERENCES public.events(id) ON DELETE SET NULL,
    member_id TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    cheki_type public.cheki_type NOT NULL DEFAULT 'solo',
    qty INTEGER NOT NULL DEFAULT 1,
    total_price INTEGER NOT NULL,
    mode VARCHAR(20) NOT NULL DEFAULT 'online',
    payment_method VARCHAR(50) DEFAULT 'transfer',
    payment_proof_url TEXT,
    status public.order_status DEFAULT 'pending',
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Order Items (opsional; backend saat ini menyimpan baris order di kolom items JSONB)
CREATE TABLE public.order_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL,
    quantity INTEGER DEFAULT 1,
    price_per_item INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) & POLICIES
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discography ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Allow ANYONE (public) to READ members, events, discography, and songs
CREATE POLICY "Public Read Members" ON public.members FOR SELECT USING (true);
CREATE POLICY "Public Read Events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Public Read Discography" ON public.discography FOR SELECT USING (true);
CREATE POLICY "Public Read Songs" ON public.songs FOR SELECT USING (true);

-- Allow ANYONE to CREATE (insert) a new order (from checkout page)
CREATE POLICY "Public Insert Orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert Order Items" ON public.order_items FOR INSERT WITH CHECK (true);

-- Note: Admin access (UPDATE/DELETE operations) can be handled by using the Supabase Service Role Key 
-- in the server environment (which bypasses RLS), so we don't need highly complex RLS policies just yet 
-- for the Admin dashboard if it calls the Express Backend.
