-- ==========================================
-- 04_admin_auth.sql
-- VIEOS Admin Authentication Setup
-- ==========================================
-- Jalankan script ini di Supabase SQL Editor
-- (Dashboard → SQL Editor → New query → Paste → Run)
-- ==========================================

-- 1. Aktifkan ekstensi pgcrypto untuk hashing password
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Buat tabel admin_users
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Masukkan data Admin
-- Catatan: Jangan menyimpan password dalam file SQL secara permanen.
-- Jalankan command INSERT secara manual di SQL Editor Supabase untuk membuat akun Admin pertama.
/*
INSERT INTO public.admin_users (username, password_hash)
VALUES ('UsernameAnda', crypt('PasswordAnda', gen_salt('bf')));
*/


-- 4. Aktifkan RLS
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- 5. Buat fungsi RPC untuk verifikasi login yang aman
-- Fungsi ini akan mengembalikan boolean (true/false)
CREATE OR REPLACE FUNCTION verify_admin(p_username TEXT, p_password TEXT)
RETURNS BOOLEAN AS $$
DECLARE
    is_valid BOOLEAN;
BEGIN
    SELECT (password_hash = crypt(p_password, password_hash))
    INTO is_valid
    FROM public.admin_users
    WHERE username = p_username;

    RETURN COALESCE(is_valid, FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Berikan akses ke fungsi verify_admin untuk publik (anon role)
GRANT EXECUTE ON FUNCTION verify_admin(TEXT, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION verify_admin(TEXT, TEXT) TO authenticated;
